//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CURDEF1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CouId { get; set; }
        public string CouName { get; set; }
        public Nullable<bool> IsSelected { get; set; }

        public List<Course> Cources { get; set; }
    }
    public class CourseModel
    {
        public List<Course> Cources { get; set; }

    }
}
